### ISSUE TITLE
源码用不了了

### ISSUE THREAD

**Issue by hmsjy2017** [BluesDawn576/bv2av#1]
PHP 7.4，输入av号或bv号后一直显示请稍等。演示站还是能用的。
![03D94C92-F76F-4E35-B9A9-4CDC82693466](https://user-images.githubusercontent.com/42692274/126802272-dcb0823b-b57e-453c-b2c5-f05f84fa7cd4.png)

**Comment by BluesDawn576** [comment]
修了，重新拉取一下源码
